version: "3"
# https://taskfile.dev/#/installation

tasks:
  gqlgen:
    desc: Generate code for GraphQL schema
    cmds:
      - go run github.com/99designs/gqlgen generate
    sources:
      - gqlgen.yml
      - models/*.go
      - graph/**/*.resolvers.go
      - graph/schema/**/*.graphqls
    generates:
      - models/models_gen.go
      - graph/**/*.resolvers.go
      - graph/generated/generated.go

  gqlgen:it:
    desc: Generate code for GraphQL schema in integration test
    dir: integration_test
    cmds:
      - npm run gql:gen
    sources:
      - src/**/*.graphql
      - ../graph/schema/**/*.graphqls
    generates:
      - src/query/index.ts

  grpcgen:
    desc: Generate code for grpc
    cmds:
      - PATH=$PATH:$(go env GOPATH)/bin protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative grpc/**/*.proto
    sources:
      - grpc/**/*.proto
    generates:
      - grpc/**/*.pb.go

  build:mock_notifier:
    desc: Builds image of mock_notifier service
    sources:
      - grpc/notifier/*.go
      - services/mock_notifier/*
    vars:
      ENV: prod
    cmds:
      - docker-compose build mock-notifier-{{.ENV}}

  log:mock_notifier:
    desc: Follow logs of mock_notifier container
    cmds:
      - (docker logs -f auction-mock-notifier-{{.ENV}}-1 | sed 's/^/[NOTIFIER] /') &

  dev:
    desc: Start dev server
    deps:
      - task: build:mock_notifier
        vars:
          ENV: dev
    env:
      SERVER_DOTENV: .server-dev.env
    cmds:
      - docker-compose --profile dev up -d
      - defer: docker-compose --profile dev stop
      - task: log:mock_notifier
        vars:
          ENV: dev
      - air

  dir:out:
    desc: Creates out directiory
    cmds:
      - mkdir -p out
    status:
      - test -d out

  build:portmocksgen:
    desc: Build tool for generating mocks of ports interfaces
    deps:
      - dir:out
    cmds:
      - go build -o out/portmocksgen.out codegen/portmocks/main.go
    sources:
      - codegen/portmocks/*.go
    generates:
      - out/portmocksgen.out

  portmocksgen:
    desc: Generates mocks for ports interfaces
    deps:
      - build:portmocksgen
    cmds:
      - out/portmocksgen.out portmocksgen.yml
      - gofmt -s -w test/*_gen.go
    sources:
      - portmocksgen.yml
      - ports/database.go
      - out/portmocksgen.out
    generates:
      - test/database.go

  filter-cover:
    desc: Filters generated files from coverage output
    cmds:
      - cat {{.IN}} | grep -v "_gen.go\|_suite.go\|generated.go\|.pb.go" > {{.OUT}}

  test:
    desc: Run test with colorful output
    cmds:
      - grc -c grc-test.conf go test {{.CLI_ARGS}}

  test:unit:
    desc: Get code coverage by unit tests
    deps:
      - dir:out
      - portmocksgen
    vars:
      TMPOUT: ./out/unit-coverage.tmp.out
      OUT: ./out/unit-coverage.out
      HTML: ./out/unit-coverage.html
    cmds:
      - go test -coverprofile={{.TMPOUT}} ./...
      # remove generated code from coverage
      - task: filter-cover
        vars:
          IN: "{{.TMPOUT}}"
          OUT: "{{.OUT}}"
      - go tool cover -html={{.OUT}} -o {{.HTML}}
      - go tool cover -func={{.OUT}}

  test:it:
    desc: Get code coverage by integration tests
    deps:
      - dir:out
      - task: build:mock_notifier
        vars:
          ENV: test
    env:
      SERVER_DOTENV: .server-test.env
      GIN_MODE: test
    vars:
      TMPOUT: ./out/it-coverage.tmp.out
      OUT: ./out/it-coverage.out
      HTML: ./out/it-coverage.html
    cmds:
      - docker-compose --profile test up --force-recreate -d
      - defer: docker-compose --profile test down
      - task: log:mock_notifier
        vars:
          ENV: test
      - go test -tags=integration -coverprofile={{.TMPOUT}} -coverpkg="auction-back/..."
      - task: filter-cover
        vars:
          IN: "{{.TMPOUT}}"
          OUT: "{{.OUT}}"
      - go tool cover -html={{.OUT}} -o {{.HTML}}
      - go tool cover -func={{.OUT}}

  test:all:
    desc: Get total code coverage by all tests
    deps:
      - test:unit
      - test:it
    vars:
      OUT: ./out/total-coverage.out
      HTML: ./out/total-coverage.html
    cmds:
      - >
        echo "mode: set" > {{.OUT}} &&
        cat ./out/*-coverage.out |
        grep -v mode: |
        sort -r |
        awk '{if($1 != last) {print $0;last=$1}}' >> {{.OUT}}
      - go tool cover -html={{.OUT}} -o {{.HTML}}
      - go tool cover -func={{.OUT}}
