// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Balance struct {
	Available float64 `json:"available"`
	Blocked   float64 `json:"blocked"`
}

type CreateProductInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type CreateProductResult struct {
	Product *Product `json:"product"`
}

type IncreaseBalanceInput struct {
	UserID string  `json:"userId"`
	Amount float64 `json:"amount"`
}

type IncreaseBalanceResult struct {
	User *User `json:"user"`
}

type Product struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Owner       *User   `json:"owner"`
}

type RegisterResult struct {
	Token string `json:"token"`
}

type User struct {
	ID      string   `json:"id"`
	Balance *Balance `json:"balance"`
}
