// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Balance struct {
	Available float64 `json:"available"`
	Blocked   float64 `json:"blocked"`
}

type CreateOfferInput struct {
	ProductID string  `json:"productId"`
	Amount    float64 `json:"amount"`
}

type CreateOfferResult struct {
	Offer *Offer `json:"offer"`
}

type CreateProductInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type CreateProductResult struct {
	Product *Product `json:"product"`
}

type IncreaseBalanceInput struct {
	UserID string  `json:"userId"`
	Amount float64 `json:"amount"`
}

type IncreaseBalanceResult struct {
	User *User `json:"user"`
}

type Offer struct {
	ID       string   `json:"id"`
	Consumer *User    `json:"consumer"`
	Product  *Product `json:"product"`
}

type OfferProductInput struct {
	ProductID string `json:"productId"`
}

type OfferProductResult struct {
	Product *Product `json:"product"`
}

type OffersConnection struct {
	PageInfo *PageInfo               `json:"pageInfo"`
	Edges    []*OffersConnectionEdge `json:"edges"`
}

type OffersConnectionEdge struct {
	Cursor string `json:"cursor"`
	Node   *Offer `json:"node"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor"`
	EndCursor       *string `json:"endCursor"`
}

type ProductConnection struct {
	PageInfo *PageInfo                `json:"pageInfo"`
	Edges    []*ProductConnectionEdge `json:"edges"`
}

type ProductConnectionEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Product `json:"node"`
}

type RegisterResult struct {
	Token string `json:"token"`
}

type RemoveOfferInput struct {
	OfferID string `json:"offerId"`
}

type RemoveOfferResult struct {
	Status string `json:"status"`
}

type SellProductInput struct {
	ProductID string `json:"productId"`
}

type SellProductResult struct {
	Product *Product `json:"product"`
}

type TakeOffProductInput struct {
	ProductID string `json:"productId"`
}

type TakeOffProductResult struct {
	Product *Product `json:"product"`
}
