version: "3.9"

services:
  db:
    build:
      dockerfile: Dockerfile.db
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    build:
      context: ./migrations
    working_dir: /usr/app
    entrypoint: ./migrate
    volumes:
      - ../migrations:/usr/app

  mock-redis:
    image: redis:6.2.6-alpine3.15
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./mock-redis.conf:/usr/local/etc/redis/redis.conf:ro

  mock-notifier:
    build:
      dockerfile: services/mock_notifier/Dockerfile
      context: ../
    ports:
      - 3000:3000

  mock-bank:
    build:
      dockerfile: services/mock_bank/Dockerfile
      context: ../
    ports:
      - 8081:8080
    
  mock-dealer:
    build:
      dockerfile: services/mock_dealer/Dockerfile
      context: ../
    ports:
      - 8082:8080
