// This file was generated by portmocksgen. DO NOT EDIT.
package ports

import (
	"auction-back/models"
	"github.com/stretchr/testify/mock"
)

type BankMock struct{ mock.Mock }

func (m *BankMock) UserFormApproved(form models.UserForm) error {
	args := m.Called(form)
	return args.Error(0)
}
