// This file was generated by portmocksgen. DO NOT EDIT.
package ports

import (
	"auction-back/models"
	"github.com/stretchr/testify/mock"
)

type RoleMock struct{ mock.Mock }

func (m *RoleMock) HasRole(roleType models.RoleType, viewer models.User) error {
	args := m.Called(roleType, viewer)
	return args.Error(0)
}
