// This file was generated by portmocksgen. DO NOT EDIT.
package ports

import (
	"auction-back/models"
	"github.com/stretchr/testify/mock"
)

type TokenMock struct{ mock.Mock }

type TokenSenderMock struct{ mock.Mock }

func (m *TokenMock) Activate(action models.TokenAction, token_code string, viewer models.User) (models.Token, error) {
	args := m.Called(action, token_code, viewer)
	return args.Get(0).(models.Token), args.Error(1)
}

func (m *TokenMock) Create(action models.TokenAction, viewer models.User, data map[string]interface{}) error {
	args := m.Called(action, viewer, data)
	return args.Error(0)
}

func (m *TokenSenderMock) Name() string {
	args := m.Called()
	return args.String(0)
}

func (m *TokenSenderMock) Send(arg0 models.Token) (bool, error) {
	args := m.Called(arg0)
	return args.Bool(0), args.Error(1)
}
