// This file was generated by gormdbopsgen. DO NOT EDIT.
package database

import (
	"auction-back/models"
	"auction-back/ports"
	"fmt"
)

type accountDB struct{ *Database }

func (d *Database) Account() ports.AccountDB { return &accountDB{d} }

func (d *accountDB) Get(id string) (models.Account, error) {
	obj := Account{}
	if err := d.db.Take(&obj, "id = ?", id).Error; err != nil {
		return models.Account{}, fmt.Errorf("take: %w", convertError(err))
	}

	return obj.into(), nil
}

func (d *accountDB) Take(config ports.AccountTakeConfig) (models.Account, error) {
	query := d.filter(d.db, config.Filter)

	obj := Account{}
	if err := query.Take(&obj).Error; err != nil {
		return models.Account{}, fmt.Errorf("take: %w", convertError(err))
	}

	return obj.into(), nil
}

func (d *accountDB) Create(account *models.Account) error {
	if account == nil {
		return ports.ErrAccountIsNil
	}
	obj := Account{}
	obj.copy(account)
	if err := d.db.Create(&obj).Error; err != nil {
		return fmt.Errorf("create: %w", convertError(err))
	}

	*account = obj.into()
	return nil
}

func (d *accountDB) Update(account *models.Account) error {
	if account == nil {
		return ports.ErrAccountIsNil
	}

	obj := Account{}
	obj.copy(account)

	if err := d.db.Save(&obj).Error; err != nil {
		return fmt.Errorf("save: %w", convertError(err))
	}
	*account = obj.into()

	return nil
}

func (d *accountDB) Pagination(first *int, after *string, filter *models.AccountsFilter) (models.AccountsConnection, error) {
	query := d.filter(d.db.Model(&Account{}), filter)
	query, err := paginationQueryByCreatedAtDesc(query, first, after)
	if err != nil {
		return models.AccountsConnection{}, fmt.Errorf("pagination: %w", err)
	}

	var objs []Account
	if err := query.Find(&objs).Error; err != nil {
		return models.AccountsConnection{}, fmt.Errorf("find: %w", err)
	}

	if len(objs) == 0 {
		return models.AccountsConnection{
			PageInfo: &models.PageInfo{},
			Edges:    make([]*models.AccountsConnectionEdge, 0),
		}, nil
	}

	hasNextPage := false

	if first != nil {
		hasNextPage = len(objs) > *first
		objs = objs[:len(objs)-1]
	}

	edges := make([]*models.AccountsConnectionEdge, 0, len(objs))

	for _, obj := range objs {
		node := obj.into()

		edges = append(edges, &models.AccountsConnectionEdge{
			Cursor: fmt.Sprintf("%v", node.ID),
			Node:   &node,
		})
	}

	startCursor := fmt.Sprintf("%v", objs[0].ID)
	endCursor := fmt.Sprintf("%v", objs[len(objs)-1].ID)

	return models.AccountsConnection{
		PageInfo: &models.PageInfo{
			HasNextPage: hasNextPage,
			StartCursor: &startCursor,
			EndCursor:   &endCursor,
		},
		Edges: edges,
	}, nil
}
