// This file was generated by gormdbopsgen. DO NOT EDIT.
package database

import (
	"auction-back/models"
	"auction-back/ports"
	"fmt"
)

type auctionDB struct{ *Database }

func (d *Database) Auction() ports.AuctionDB { return &auctionDB{d} }

func (d *auctionDB) Get(id string) (models.Auction, error) {
	obj := Auction{}
	if err := d.db.Take(&obj, "id = ?", id).Error; err != nil {
		return models.Auction{}, fmt.Errorf("take: %w", convertError(err))
	}

	return obj.into(), nil
}

func (d *auctionDB) Take(config ports.AuctionTakeConfig) (models.Auction, error) {
	query := d.filter(d.db, config.Filter)

	obj := Auction{}
	if err := query.Take(&obj).Error; err != nil {
		return models.Auction{}, fmt.Errorf("take: %w", convertError(err))
	}

	return obj.into(), nil
}

func (d *auctionDB) Create(auction *models.Auction) error {
	if auction == nil {
		return ports.ErrAuctionIsNil
	}
	obj := Auction{}
	obj.copy(auction)
	if err := d.db.Create(&obj).Error; err != nil {
		return fmt.Errorf("create: %w", convertError(err))
	}

	*auction = obj.into()
	return nil
}

func (d *auctionDB) Update(auction *models.Auction) error {
	if auction == nil {
		return ports.ErrAuctionIsNil
	}

	obj := Auction{}
	obj.copy(auction)

	if err := d.db.Save(&obj).Error; err != nil {
		return fmt.Errorf("save: %w", convertError(err))
	}
	*auction = obj.into()

	return nil
}

func (d *auctionDB) Pagination(first *int, after *string, filter *models.AuctionsFilter) (models.AuctionsConnection, error) {
	query := d.filter(d.db.Model(&Auction{}), filter)
	query, err := paginationQueryByCreatedAtDesc(query, first, after)
	if err != nil {
		return models.AuctionsConnection{}, fmt.Errorf("pagination: %w", err)
	}

	var objs []Auction
	if err := query.Find(&objs).Error; err != nil {
		return models.AuctionsConnection{}, fmt.Errorf("find: %w", err)
	}

	if len(objs) == 0 {
		return models.AuctionsConnection{
			PageInfo: &models.PageInfo{},
			Edges:    make([]*models.AuctionsConnectionEdge, 0),
		}, nil
	}

	hasNextPage := false

	if first != nil {
		hasNextPage = len(objs) > *first
		objs = objs[:len(objs)-1]
	}

	edges := make([]*models.AuctionsConnectionEdge, 0, len(objs))

	for _, obj := range objs {
		node := obj.into()

		edges = append(edges, &models.AuctionsConnectionEdge{
			Cursor: fmt.Sprintf("%v", node.ID),
			Node:   &node,
		})
	}

	startCursor := fmt.Sprintf("%v", objs[0].ID)
	endCursor := fmt.Sprintf("%v", objs[len(objs)-1].ID)

	return models.AuctionsConnection{
		PageInfo: &models.PageInfo{
			HasNextPage: hasNextPage,
			StartCursor: &startCursor,
			EndCursor:   &endCursor,
		},
		Edges: edges,
	}, nil
}
