// This file was generated by gormdbopsgen. DO NOT EDIT.
package database

import (
	"auction-back/models"
	"auction-back/ports"
	"fmt"
)

type dealStateDB struct{ *Database }

func (d *Database) DealState() ports.DealStateDB { return &dealStateDB{d} }

func (d *dealStateDB) Get(id string) (models.DealState, error) {
	obj := DealState{}
	if err := d.db.Take(&obj, "id = ?", id).Error; err != nil {
		return models.DealState{}, fmt.Errorf("take: %w", convertError(err))
	}

	return obj.into(), nil
}

func (d *dealStateDB) Create(dealState *models.DealState) error {
	if dealState == nil {
		return ports.ErrDealStateIsNil
	}
	obj := DealState{}
	obj.copy(dealState)
	if err := d.db.Create(&obj).Error; err != nil {
		return fmt.Errorf("create: %w", convertError(err))
	}

	*dealState = obj.into()
	return nil
}
