// This file was generated by gormdbopsgen. DO NOT EDIT.
package database

import (
	"auction-back/models"
	"auction-back/ports"
	"fmt"
)

type offerDB struct{ *Database }

func (d *Database) Offer() ports.OfferDB { return &offerDB{d} }

func (d *offerDB) Get(id string) (models.Offer, error) {
	obj := Offer{}
	if err := d.db.Take(&obj, "id = ?", id).Error; err != nil {
		return models.Offer{}, fmt.Errorf("take: %w", convertError(err))
	}

	return obj.into(), nil
}

func (d *offerDB) Create(offer *models.Offer) error {
	if offer == nil {
		return ports.ErrOfferIsNil
	}
	obj := Offer{}
	obj.copy(offer)
	if err := d.db.Create(&obj).Error; err != nil {
		return fmt.Errorf("create: %w", convertError(err))
	}

	*offer = obj.into()
	return nil
}

func (d *offerDB) Update(offer *models.Offer) error {
	if offer == nil {
		return ports.ErrOfferIsNil
	}

	obj := Offer{}
	obj.copy(offer)

	if err := d.db.Save(&obj).Error; err != nil {
		return fmt.Errorf("save: %w", convertError(err))
	}
	*offer = obj.into()

	return nil
}

func (d *offerDB) Pagination(first *int, after *string, filter *models.OffersFilter) (models.OffersConnection, error) {
	query := d.filter(d.db.Model(&Offer{}), filter)
	query, err := paginationQueryByCreatedAtDesc(query, first, after)
	if err != nil {
		return models.OffersConnection{}, fmt.Errorf("pagination: %w", err)
	}

	var objs []Offer
	if err := query.Find(&objs).Error; err != nil {
		return models.OffersConnection{}, fmt.Errorf("find: %w", err)
	}

	if len(objs) == 0 {
		return models.OffersConnection{
			PageInfo: &models.PageInfo{},
			Edges:    make([]*models.OffersConnectionEdge, 0),
		}, nil
	}

	hasNextPage := false

	if first != nil {
		hasNextPage = len(objs) > *first
		objs = objs[:len(objs)-1]
	}

	edges := make([]*models.OffersConnectionEdge, 0, len(objs))

	for _, obj := range objs {
		node := obj.into()

		edges = append(edges, &models.OffersConnectionEdge{
			Cursor: fmt.Sprintf("%v", node.ID),
			Node:   &node,
		})
	}

	startCursor := fmt.Sprintf("%v", objs[0].ID)
	endCursor := fmt.Sprintf("%v", objs[len(objs)-1].ID)

	return models.OffersConnection{
		PageInfo: &models.PageInfo{
			HasNextPage: hasNextPage,
			StartCursor: &startCursor,
			EndCursor:   &endCursor,
		},
		Edges: edges,
	}, nil
}
