// This file was generated by gormdbopsgen. DO NOT EDIT.
package database

import (
	"auction-back/models"
	"auction-back/ports"
	"fmt"
)

type productDB struct{ *Database }

func (d *Database) Product() ports.ProductDB { return &productDB{d} }

func (d *productDB) Get(id string) (models.Product, error) {
	obj := Product{}
	if err := d.db.Take(&obj, "id = ?", id).Error; err != nil {
		return models.Product{}, fmt.Errorf("take: %w", convertError(err))
	}

	return obj.into(), nil
}

func (d *productDB) Create(product *models.Product) error {
	if product == nil {
		return ports.ErrProductIsNil
	}
	obj := Product{}
	obj.copy(product)
	if err := d.db.Create(&obj).Error; err != nil {
		return fmt.Errorf("create: %w", convertError(err))
	}

	*product = obj.into()
	return nil
}

func (d *productDB) Update(product *models.Product) error {
	if product == nil {
		return ports.ErrProductIsNil
	}

	obj := Product{}
	obj.copy(product)

	if err := d.db.Save(&obj).Error; err != nil {
		return fmt.Errorf("save: %w", convertError(err))
	}
	*product = obj.into()

	return nil
}

func (d *productDB) Pagination(first *int, after *string, filter *models.ProductsFilter) (models.ProductsConnection, error) {
	query := d.filter(d.db.Model(&Product{}), filter)
	query, err := paginationQueryByCreatedAtDesc(query, first, after)
	if err != nil {
		return models.ProductsConnection{}, fmt.Errorf("pagination: %w", err)
	}

	var objs []Product
	if err := query.Find(&objs).Error; err != nil {
		return models.ProductsConnection{}, fmt.Errorf("find: %w", err)
	}

	if len(objs) == 0 {
		return models.ProductsConnection{
			PageInfo: &models.PageInfo{},
			Edges:    make([]*models.ProductsConnectionEdge, 0),
		}, nil
	}

	hasNextPage := false

	if first != nil {
		hasNextPage = len(objs) > *first
		objs = objs[:len(objs)-1]
	}

	edges := make([]*models.ProductsConnectionEdge, 0, len(objs))

	for _, obj := range objs {
		node := obj.into()

		edges = append(edges, &models.ProductsConnectionEdge{
			Cursor: fmt.Sprintf("%v", node.ID),
			Node:   &node,
		})
	}

	startCursor := fmt.Sprintf("%v", objs[0].ID)
	endCursor := fmt.Sprintf("%v", objs[len(objs)-1].ID)

	return models.ProductsConnection{
		PageInfo: &models.PageInfo{
			HasNextPage: hasNextPage,
			StartCursor: &startCursor,
			EndCursor:   &endCursor,
		},
		Edges: edges,
	}, nil
}
