// This file was generated by gormdbopsgen. DO NOT EDIT.
package database

import (
	"auction-back/models"
	"auction-back/ports"
	"fmt"
)

type tokenDB struct{ *Database }

func (d *Database) Token() ports.TokenDB { return &tokenDB{d} }

func (d *tokenDB) Create(token *models.Token) error {
	if token == nil {
		return ports.ErrTokenIsNil
	}
	obj := Token{}
	obj.copy(token)
	if err := d.db.Create(&obj).Error; err != nil {
		return fmt.Errorf("create: %w", convertError(err))
	}

	*token = obj.into()
	return nil
}

func (d *tokenDB) Update(token *models.Token) error {
	if token == nil {
		return ports.ErrTokenIsNil
	}

	obj := Token{}
	obj.copy(token)

	if err := d.db.Save(&obj).Error; err != nil {
		return fmt.Errorf("save: %w", convertError(err))
	}
	*token = obj.into()

	return nil
}
