// This file was generated by gormdbopsgen. DO NOT EDIT.
package database

import (
	"auction-back/models"
	"auction-back/ports"
	"fmt"
)

type userDB struct{ *Database }

func (d *Database) User() ports.UserDB { return &userDB{d} }

func (d *userDB) Get(id string) (models.User, error) {
	obj := User{}
	if err := d.db.Take(&obj, "id = ?", id).Error; err != nil {
		return models.User{}, fmt.Errorf("take: %w", convertError(err))
	}

	return obj.into(), nil
}

func (d *userDB) Create(user *models.User) error {
	if user == nil {
		return ports.ErrUserIsNil
	}
	obj := User{}
	obj.copy(user)
	if err := d.db.Create(&obj).Error; err != nil {
		return fmt.Errorf("create: %w", convertError(err))
	}

	*user = obj.into()
	return nil
}

func (d *userDB) Pagination(first *int, after *string, filter *models.UsersFilter) (models.UsersConnection, error) {
	query := d.filter(d.db.Model(&User{}), filter)
	query, err := paginationQueryByCreatedAtDesc(query, first, after)
	if err != nil {
		return models.UsersConnection{}, fmt.Errorf("pagination: %w", err)
	}

	var objs []User
	if err := query.Find(&objs).Error; err != nil {
		return models.UsersConnection{}, fmt.Errorf("find: %w", err)
	}

	if len(objs) == 0 {
		return models.UsersConnection{
			PageInfo: &models.PageInfo{},
			Edges:    make([]*models.UsersConnectionEdge, 0),
		}, nil
	}

	hasNextPage := false

	if first != nil {
		hasNextPage = len(objs) > *first
		objs = objs[:len(objs)-1]
	}

	edges := make([]*models.UsersConnectionEdge, 0, len(objs))

	for _, obj := range objs {
		node := obj.into()

		edges = append(edges, &models.UsersConnectionEdge{
			Cursor: fmt.Sprintf("%v", node.ID),
			Node:   &node,
		})
	}

	startCursor := fmt.Sprintf("%v", objs[0].ID)
	endCursor := fmt.Sprintf("%v", objs[len(objs)-1].ID)

	return models.UsersConnection{
		PageInfo: &models.PageInfo{
			HasNextPage: hasNextPage,
			StartCursor: &startCursor,
			EndCursor:   &endCursor,
		},
		Edges: edges,
	}, nil
}
