// This file was generated by gormdbopsgen. DO NOT EDIT.
package database

import (
	"auction-back/models"
	"auction-back/ports"
	"fmt"
)

type userFormDB struct{ *Database }

func (d *Database) UserForm() ports.UserFormDB { return &userFormDB{d} }

func (d *userFormDB) Get(id string) (models.UserForm, error) {
	obj := UserForm{}
	if err := d.db.Take(&obj, "id = ?", id).Error; err != nil {
		return models.UserForm{}, fmt.Errorf("take: %w", convertError(err))
	}

	return obj.into(), nil
}

func (d *userFormDB) Create(userForm *models.UserForm) error {
	if userForm == nil {
		return ports.ErrUserFormIsNil
	}
	obj := UserForm{}
	obj.copy(userForm)
	if err := d.db.Create(&obj).Error; err != nil {
		return fmt.Errorf("create: %w", convertError(err))
	}

	*userForm = obj.into()
	return nil
}

func (d *userFormDB) Update(userForm *models.UserForm) error {
	if userForm == nil {
		return ports.ErrUserFormIsNil
	}

	obj := UserForm{}
	obj.copy(userForm)

	if err := d.db.Save(&obj).Error; err != nil {
		return fmt.Errorf("save: %w", convertError(err))
	}
	*userForm = obj.into()

	return nil
}

func (d *userFormDB) Pagination(first *int, after *string, filter *models.UserFormsFilter) (models.UserFormsConnection, error) {
	query := d.filter(d.db.Model(&UserForm{}), filter)
	query, err := paginationQueryByCreatedAtDesc(query, first, after)
	if err != nil {
		return models.UserFormsConnection{}, fmt.Errorf("pagination: %w", err)
	}

	var objs []UserForm
	if err := query.Find(&objs).Error; err != nil {
		return models.UserFormsConnection{}, fmt.Errorf("find: %w", err)
	}

	if len(objs) == 0 {
		return models.UserFormsConnection{
			PageInfo: &models.PageInfo{},
			Edges:    make([]*models.UserFormsConnectionEdge, 0),
		}, nil
	}

	hasNextPage := false

	if first != nil {
		hasNextPage = len(objs) > *first
		objs = objs[:len(objs)-1]
	}

	edges := make([]*models.UserFormsConnectionEdge, 0, len(objs))

	for _, obj := range objs {
		node := obj.into()

		edges = append(edges, &models.UserFormsConnectionEdge{
			Cursor: fmt.Sprintf("%v", node.ID),
			Node:   &node,
		})
	}

	startCursor := fmt.Sprintf("%v", objs[0].ID)
	endCursor := fmt.Sprintf("%v", objs[len(objs)-1].ID)

	return models.UserFormsConnection{
		PageInfo: &models.PageInfo{
			HasNextPage: hasNextPage,
			StartCursor: &startCursor,
			EndCursor:   &endCursor,
		},
		Edges: edges,
	}, nil
}
